# Generated by Django 2.1.dev20180313180640 on 2018-04-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=240)),
                ('contact_number', models.CharField(max_length=240)),
                ('contact_email', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
            ],
        ),
    ]
