# Generated by Django 2.1.dev20180313180640 on 2018-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
